# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(985, 502)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.XFigure = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XFigure.sizePolicy().hasHeightForWidth())
        self.XFigure.setSizePolicy(sizePolicy)
        self.XFigure.setMinimumSize(QtCore.QSize(0, 250))
        self.XFigure.setObjectName("XFigure")
        self.verticalLayout_3.addWidget(self.XFigure)
        self.widget_2 = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setStyleSheet("QWidget#widget{\n"
"    border: 2px solid #000000; border-radius: 5px;}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.BPMName = QtWidgets.QLineEdit(self.widget)
        self.BPMName.setObjectName("BPMName")
        self.gridLayout_3.addWidget(self.BPMName, 0, 2, 1, 2)
        self.BPMChannel_X = QtWidgets.QLineEdit(self.widget)
        self.BPMChannel_X.setObjectName("BPMChannel_X")
        self.gridLayout_3.addWidget(self.BPMChannel_X, 1, 2, 1, 2)
        self.StopBtn = QtWidgets.QPushButton(self.widget)
        self.StopBtn.setObjectName("StopBtn")
        self.gridLayout_3.addWidget(self.StopBtn, 3, 3, 1, 1)
        self.StartBtn = QtWidgets.QPushButton(self.widget)
        self.StartBtn.setObjectName("StartBtn")
        self.gridLayout_3.addWidget(self.StartBtn, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.BPMChannel_Y = QtWidgets.QLineEdit(self.widget)
        self.BPMChannel_Y.setObjectName("BPMChannel_Y")
        self.gridLayout_3.addWidget(self.BPMChannel_Y, 2, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.isSaveCheckBox = QtWidgets.QCheckBox(self.widget)
        self.isSaveCheckBox.setObjectName("isSaveCheckBox")
        self.verticalLayout_2.addWidget(self.isSaveCheckBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.SetSaveInfo = QtWidgets.QWidget(self.widget)
        self.SetSaveInfo.setObjectName("SetSaveInfo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.SetSaveInfo)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.SetSaveInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.FilePath = QtWidgets.QLineEdit(self.SetSaveInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilePath.sizePolicy().hasHeightForWidth())
        self.FilePath.setSizePolicy(sizePolicy)
        self.FilePath.setObjectName("FilePath")
        self.horizontalLayout_2.addWidget(self.FilePath)
        self.FilePathBtn = QtWidgets.QPushButton(self.SetSaveInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FilePathBtn.sizePolicy().hasHeightForWidth())
        self.FilePathBtn.setSizePolicy(sizePolicy)
        self.FilePathBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.FilePathBtn.setObjectName("FilePathBtn")
        self.horizontalLayout_2.addWidget(self.FilePathBtn)
        self.verticalLayout_2.addWidget(self.SetSaveInfo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setStyleSheet("QWidget#widget_3{\n"
"    border: 2px solid #000000; border-radius: 5px;}")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 3, 1, 1)
        self.QM_I = QtWidgets.QDoubleSpinBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QM_I.sizePolicy().hasHeightForWidth())
        self.QM_I.setSizePolicy(sizePolicy)
        self.QM_I.setMinimumSize(QtCore.QSize(158, 25))
        self.QM_I.setMaximum(9999999.0)
        self.QM_I.setSingleStep(0.2)
        self.QM_I.setObjectName("QM_I")
        self.gridLayout_2.addWidget(self.QM_I, 3, 2, 1, 1)
        self.QM_C = QtWidgets.QSpinBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QM_C.sizePolicy().hasHeightForWidth())
        self.QM_C.setSizePolicy(sizePolicy)
        self.QM_C.setMinimumSize(QtCore.QSize(158, 25))
        self.QM_C.setMinimum(1)
        self.QM_C.setMaximum(999999)
        self.QM_C.setObjectName("QM_C")
        self.gridLayout_2.addWidget(self.QM_C, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.QMChannel = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QMChannel.sizePolicy().hasHeightForWidth())
        self.QMChannel.setSizePolicy(sizePolicy)
        self.QMChannel.setMinimumSize(QtCore.QSize(158, 25))
        self.QMChannel.setObjectName("QMChannel")
        self.gridLayout_2.addWidget(self.QMChannel, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 3, 1, 1)
        self.QMPutBtn = QtWidgets.QPushButton(self.widget_3)
        self.QMPutBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.QMPutBtn.setObjectName("QMPutBtn")
        self.gridLayout_2.addWidget(self.QMPutBtn, 4, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(20, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 4)
        self.QM_A = QtWidgets.QDoubleSpinBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QM_A.sizePolicy().hasHeightForWidth())
        self.QM_A.setSizePolicy(sizePolicy)
        self.QM_A.setMinimumSize(QtCore.QSize(158, 25))
        self.QM_A.setSingleStep(0.2)
        self.QM_A.setObjectName("QM_A")
        self.gridLayout_2.addWidget(self.QM_A, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.widget_3)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 3, 3, 1, 1)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("QWidget#widget_4{\n"
"    border: 2px solid #000000; border-radius: 5px;}")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 5, 0, 1, 1)
        self.DMChannel = QtWidgets.QLineEdit(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DMChannel.sizePolicy().hasHeightForWidth())
        self.DMChannel.setSizePolicy(sizePolicy)
        self.DMChannel.setObjectName("DMChannel")
        self.gridLayout_4.addWidget(self.DMChannel, 5, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 3)
        self.DM_C = QtWidgets.QDoubleSpinBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DM_C.sizePolicy().hasHeightForWidth())
        self.DM_C.setSizePolicy(sizePolicy)
        self.DM_C.setMinimumSize(QtCore.QSize(158, 25))
        self.DM_C.setMinimum(-999999.0)
        self.DM_C.setMaximum(999999.0)
        self.DM_C.setSingleStep(0.2)
        self.DM_C.setObjectName("DM_C")
        self.gridLayout_4.addWidget(self.DM_C, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_4)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 2, 1, 1)
        self.DMPutBtn = QtWidgets.QPushButton(self.widget_4)
        self.DMPutBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.DMPutBtn.setObjectName("DMPutBtn")
        self.gridLayout_4.addWidget(self.DMPutBtn, 5, 2, 1, 1)
        self.DM_I = QtWidgets.QDoubleSpinBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DM_I.sizePolicy().hasHeightForWidth())
        self.DM_I.setSizePolicy(sizePolicy)
        self.DM_I.setMinimumSize(QtCore.QSize(158, 25))
        self.DM_I.setMaximum(9999999.0)
        self.DM_I.setSingleStep(0.2)
        self.DM_I.setObjectName("DM_I")
        self.gridLayout_4.addWidget(self.DM_I, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_4)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.errorDisplay = QtWidgets.QLabel(self.widget_4)
        self.errorDisplay.setText("")
        self.errorDisplay.setObjectName("errorDisplay")
        self.verticalLayout.addWidget(self.errorDisplay)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.widget_4)
        self.verticalLayout_3.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "X Channel:"))
        self.StopBtn.setText(_translate("Form", "Stop"))
        self.StartBtn.setText(_translate("Form", "Start"))
        self.label.setText(_translate("Form", "BPM:"))
        self.label_3.setText(_translate("Form", "Y Channel:"))
        self.isSaveCheckBox.setText(_translate("Form", "Save Data"))
        self.label_4.setText(_translate("Form", "File Path:"))
        self.FilePathBtn.setText(_translate("Form", "..."))
        self.label_13.setText(_translate("Form", "A"))
        self.label_7.setText(_translate("Form", "Interval:"))
        self.label_8.setText(_translate("Form", "Channel:"))
        self.label_11.setText(_translate("Form", "S"))
        self.QMPutBtn.setText(_translate("Form", "Put"))
        self.label_9.setText(_translate("Form", "Quadrupole Magnet Current Setting"))
        self.label_6.setText(_translate("Form", "Cycle:"))
        self.label_5.setText(_translate("Form", "Amplitude："))
        self.label_15.setText(_translate("Form", "S"))
        self.label_12.setText(_translate("Form", "Current："))
        self.label_14.setText(_translate("Form", "Channel:"))
        self.label_10.setText(_translate("Form", "Dipole Magnet Current Setting"))
        self.label_16.setText(_translate("Form", "A"))
        self.DMPutBtn.setText(_translate("Form", "Put"))
        self.label_17.setText(_translate("Form", "Interval:"))
        self.label_18.setText(_translate("Form", "S"))
